# 需求：
# 1.  在Spring Boot中，可以使用多环境配置来根据不同的运行环境（如开发、测试、生产）加载不同的配置。
#     SpringBoot支持多环境配置让应用程序在不同的环境中使用不同的配置参数，例如数据库连接信息、日志级别、缓存配置等。
# 2.  后期实际写的配置可能会很多，为了方便管理，可以分别写成多个yml子文件

# 只需在主配置文件中用 spring.profiles.active 属性激活yml子文件即可 使用效果与在主配置文件中一样
# 如果设置了spring.profiles.active，并且和主配置文件有重叠属性，以子配置文件设置优先。

test:
  username: hello